# Generated by Django 3.0.5 on 2020-04-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Опубликована ли страница?', verbose_name='Активная')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL адрес страницы')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Текст страницы')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
