# Generated by Django 3.0.5 on 2020-04-22 15:52

import apps.shop.models
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Опубликован ли товар?', verbose_name='Активный')),
                ('sku', models.CharField(max_length=50, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена без скидки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('main_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.shop.models.main_image_upload_path, verbose_name='Главное изображение')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='shop.Categories', verbose_name='Категории товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.shop.models.product_image_upload_path, verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
    ]
